# Generated by Django 4.2.3 on 2023-07-26 09:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('services', '0005_coursetype_is_deleted'),
    ]

    operations = [
        migrations.CreateModel(
            name='University',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('university_logo', models.ImageField(blank=True, null=True, upload_to='Images')),
                ('university_name', models.CharField(blank=True, max_length=300, null=True)),
                ('about_university', models.TextField(blank=True, null=True)),
                ('sample_certificate', models.ImageField(blank=True, null=True, upload_to='Images')),
                ('prospectus', models.FileField(blank=True, null=True, upload_to='Files')),
                ('is_deleted', models.BooleanField(default=False)),
                ('coursetype', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='services.coursetype')),
                ('service', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='services.servicetype')),
            ],
            options={
                'db_table': 'University',
            },
        ),
    ]
