# Generated by Django 4.2.3 on 2023-07-29 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(blank=True, max_length=200, null=True)),
                ('flag', models.ImageField(blank=True, null=True, upload_to='Images')),
            ],
            options={
                'db_table': 'Country',
            },
        ),
    ]
