# Generated by Django 4.2.3 on 2023-07-31 04:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0003_facts_course_approval'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='course',
            options={'ordering': ('course_name',)},
        ),
    ]
