# Generated by Django 4.2.3 on 2023-07-31 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0005_alter_course_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='country',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
