# Generated by Django 4.2.3 on 2023-07-28 06:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0007_course'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Course',
        ),
    ]
