# Generated by Django 4.2.3 on 2023-08-03 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0007_coursespecialization'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursespecialization',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
