# Generated by Django 4.2.3 on 2023-08-04 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0008_coursespecialization_is_deleted'),
    ]

    operations = [
        migrations.CreateModel(
            name='Faq',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('faq_question', models.TextField(blank=True, null=True)),
                ('faq_answer', models.TextField(blank=True, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'Faq',
            },
        ),
    ]
