# Generated by Django 4.2.3 on 2023-07-28 07:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0009_course'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='Fees',
            new_name='fees',
        ),
        migrations.RenameField(
            model_name='course',
            old_name='Fees_description',
            new_name='fees_description',
        ),
    ]
