# Generated by Django 4.2.3 on 2023-07-28 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0010_rename_fees_course_fees_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='university',
            name='country',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
