# Generated by Django 4.2.3 on 2023-08-16 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0011_foodfacility'),
    ]

    operations = [
        migrations.AddField(
            model_name='foodfacility',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
