# Generated by Django 4.2.3 on 2023-08-18 07:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0012_foodfacility_is_deleted'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hostel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hostel_name', models.CharField(blank=True, max_length=200, null=True)),
                ('hostel_image', models.ImageField(blank=True, null=True, upload_to='Images')),
                ('distance', models.CharField(blank=True, max_length=200, null=True)),
                ('fees', models.IntegerField(blank=True, null=True)),
                ('university', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='course.university')),
            ],
            options={
                'db_table': 'Hostel',
            },
        ),
    ]
