# Generated by Django 4.2.3 on 2023-08-18 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0013_hostel'),
    ]

    operations = [
        migrations.AddField(
            model_name='hostel',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
