# Generated by Django 4.2.3 on 2023-07-26 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0002_options_is_deleted_questions_is_deleted_recordanswer'),
    ]

    operations = [
        migrations.AddField(
            model_name='recordanswer',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
