# Generated by Django 4.2.3 on 2023-07-24 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='register',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
