# Generated by Django 4.2.3 on 2023-07-31 09:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0003_recordanswer_is_deleted'),
        ('general', '0002_register_is_deleted'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Register',
            new_name='StudentProfile',
        ),
        migrations.AlterModelTable(
            name='studentprofile',
            table='StudentProfile',
        ),
    ]
