# Generated by Django 4.2.3 on 2023-08-01 05:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0005_remove_chiefprofile_role_delete_role'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ChiefProfile',
        ),
    ]
