# Generated by Django 4.2.3 on 2023-08-09 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0008_studentprofile_password_studentprofile_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='status',
            field=models.CharField(default='processing', max_length=200),
        ),
    ]
