# Generated by Django 4.2.3 on 2023-08-09 10:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0009_studentprofile_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentprofile',
            name='status',
        ),
    ]
