# Generated by Django 4.2.3 on 2023-08-15 05:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0010_remove_studentprofile_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='studentprofile',
            options={},
        ),
    ]
