# Generated by Django 4.2.3 on 2023-07-19 06:27

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceType',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('service', models.CharField(blank=True, max_length=300, null=True)),
            ],
            options={
                'verbose_name': 'ServiceType',
                'verbose_name_plural': 'ServiceTypes',
                'db_table': 'ServiceType',
                'ordering': ('id',),
            },
        ),
        migrations.CreateModel(
            name='CourseType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_type', models.CharField(max_length=100)),
                ('service', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='services.servicetype')),
            ],
            options={
                'db_table': 'CourseType',
            },
        ),
    ]
