# Generated by Django 4.2.3 on 2023-07-25 06:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_servicetype_is_deleted'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CourseType',
        ),
    ]
