# Generated by Django 4.2.3 on 2023-07-25 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0004_coursetype'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursetype',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
