# Generated by Django 4.2.3 on 2023-07-19 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='Images')),
                ('about', models.TextField(blank=True, null=True)),
                ('address', models.CharField(blank=True, max_length=500, null=True)),
                ('phone', models.BigIntegerField(blank=True, null=True)),
                ('email', models.CharField(blank=True, max_length=200, null=True)),
                ('facebook_url', models.URLField(blank=True, null=True)),
                ('instagram_url', models.URLField(blank=True, null=True)),
                ('youtube_url', models.URLField(blank=True, null=True)),
                ('whatsapp_url', models.URLField(blank=True, null=True)),
                ('linkedln_url', models.URLField(blank=True, null=True)),
            ],
            options={
                'db_table': 'Contact',
            },
        ),
        migrations.CreateModel(
            name='Details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(blank=True, max_length=300, null=True)),
                ('body', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='Images')),
                ('title', models.CharField(blank=True, max_length=200, null=True)),
                ('content', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'Details',
            },
        ),
        migrations.CreateModel(
            name='Experts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=300, null=True)),
                ('content', models.TextField(blank=True, null=True)),
                ('name', models.CharField(blank=True, max_length=200, null=True)),
                ('role', models.CharField(blank=True, max_length=200, null=True)),
                ('experience', models.CharField(blank=True, max_length=200, null=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='Images')),
                ('rating', models.IntegerField(blank=True, null=True)),
                ('counselling', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'Experts',
            },
        ),
        migrations.CreateModel(
            name='HomeDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('main_banner', models.ImageField(blank=True, null=True, upload_to='Images')),
                ('main_banner_url', models.URLField(blank=True, null=True)),
                ('sub_banner', models.ImageField(blank=True, null=True, upload_to='Images')),
                ('sub_banner_url', models.URLField(blank=True, null=True)),
                ('project_logo', models.ImageField(blank=True, null=True, upload_to='Images')),
            ],
            options={
                'db_table': 'HomeDetails',
            },
        ),
    ]
