# Generated by Django 4.2.3 on 2023-07-25 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_homedetails_is_deleted'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
