# Generated by Django 4.2.3 on 2023-08-02 05:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_experts_is_deleted'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homedetails',
            name='sub_banner',
        ),
        migrations.RemoveField(
            model_name='homedetails',
            name='sub_banner_url',
        ),
    ]
