# Generated by Django 4.2.3 on 2023-08-02 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_remove_homedetails_sub_banner_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subbanner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sub_banner_url', models.URLField(blank=True, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'Subbanner',
            },
        ),
    ]
