# Generated by Django 4.2.3 on 2023-08-02 08:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_subbanner_sub_banner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homedetails',
            name='project_logo',
        ),
    ]
