# Generated by Django 4.2.3 on 2023-08-02 08:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_remove_homedetails_project_logo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='logo',
        ),
    ]
