# Generated by Django 4.2.3 on 2023-08-11 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_remove_contact_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='homedetails',
            name='status',
            field=models.CharField(default='hide', max_length=128),
        ),
    ]
