# Generated by Django 4.2.3 on 2023-08-11 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_homedetails_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homedetails',
            name='status',
            field=models.CharField(default='active', max_length=128),
        ),
    ]
