# Generated by Django 4.2.3 on 2023-08-11 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_alter_homedetails_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='subbanner',
            name='status',
            field=models.CharField(default='active', max_length=128),
        ),
    ]
